# Zorggebruik jeugd

## Gebruik jeugdhulp   
In 2016 maakte 13.2% van de jongeren in Den Haag gebruik van Jeugdhulp (zie figuur xx). Gelet op de achtergrond van jongeren die gebruik maken van Jeugdhulp, valt op dat het gebruik van jeugd-hulp bij Antilliaans-Nederlandse jongeren twee keer hoger is dan gemiddeld (31% ten opzichte van 15% gemiddeld). Ook bij de inwoners met een Surinaamse achtergrond is het gebruik van jeugd-hulp relatief hoog (19%). Marokkaans-Nederlandse en Turks-Nederlandse jongeren maken daar-entegen relatief weer minder dan gemiddeld gebruik van jeugdhulp. Deze jongeren zijn echter, samen met de Antilliaans-Nederlandse jongeren, wel oververtegenwoordigd in de jeugdreclasse-ring. Dit beeld is zichtbaar in alle G4-steden.   


## Jeugdhulp door wijk- en buurtteams   
In 2016 heeft 8% van de Haagse jeugd, hulp ontvangen via een wijk- of buurtteam. Relatief veel Antilliaans-Nederlandse jongeren maken gebruik van de wijk- of buurtteams (21%). Ook de Suri-naams-Nederlandse jongeren (11%) en Marokkaans-Nederlandse jongeren (9%) maken relatief veel gebruik van de wijk- en buurtteams.

## Jeugdreclassering   
In 2016 had 0,8% van de jongeren in Den Haag een maatregel jeugdreclassering. Dit betrof relatief veel jongeren met een Antilliaanse (2,0%) en Marokkaanse achtergrond (1,8%). Ook Amsterdam en Rotterdam hadden relatief veel jongeren met een Antilliaanse achtergrond die te maken had-den met de Jeugdreclassering. Op de tweede plaats gevolgd door jongeren met een Surinaamse achtergrond. Utrecht geeft een ander beeld. Antilliaans- en Surinaams-Nederlandse jongeren zijn juist ondervertegenwoordigd.  

## Mogelijke verklaringen      
Factoren die verklaren waarom Antilliaans-Nederlandse jongeren meer dan gemiddeld gebruik maken van verschillende vormen van jeugdhulp, kunnen zowel gevonden worden op het niveau van de jongere zelf als op gezinsniveau.

*Niveau van de jongere*   
Antilliaans-Nederlandse jongeren hebben relatief vaak emotionele problemen of gedragsproble-men. Tevens hebben ze vaker last van hyperactiviteit en een aandachtstekort en is er vaker sprake van problemen met leeftijdsgenoten. Daarnaast is hun opleidingsniveau gemiddeld lager en komt voortijdig schooluitval vaker voor. Ten slotte worden jongeren met een Antilliaanse achtergrond vaker verdacht van een delict, waardoor ze vaker met de jeugdreclassering te maken hebben.

*Gezinsniveau*   
Op het niveau van het gezin spelen factoren zoals eennoudergezinnen en werkloos-heid/uitkeringsgezinnen mee. Daarnaast hebben ouders met een Antilliaanse achtergrond relatief vaak een negatieve beleving van hun eigen opvoedingscompetentie en is er in deze gezinnen rela-tief vaak sprake van opvoed- en opgroeiproblemen.   

Al deze factoren samen verklaren het relatief hoge gebruik van de verschillende vormen van jeugdzorg [@Gilsing2015].
  

