# Conclusies

Het geheel overziende valt het op dat relatief veel Haagse bewoners met een Antilliaanse achter-grond kampen met maatschappelijke problemen. Op een aantal gebieden zijn het zorgwekkende cijfers.   

Wat het **onderwijs** betreft zien wij dat het deel dat een laag opleidingsniveau heeft, vergeleken met andere groepen met een migratieachtergrond kleiner is. Het is in Den Haag gelijk aan het ge-middelde. Vergeleken met het landelijk beeld zijn er minder laagopgeleiden en meer hoogopgelei-de inwoners met een Antilliaanse achtergrond in Den Haag. Hier liggen de zorgen dus niet. Maar wat voortijdig schooluitval betreft zijn de cijfers wel verontrustend.   

Het aandeel **uitkeringsgerechtigden** in de leeftijdscategorie 15-64 jaar is onder Antilliaans-Nederlandse inwoners erg hoog. Samen met Marokkaanse Nederlanders het hoogste. Onder de jongere inwoners (15-24 jaar) in Den Haag is gemiddeld 2,3% uitkeringsgerechtigd. Bij Antilliaans-Nederlandse inwoners ligt dit op 4,2%. Kijken we naar andere leeftijden zijn de verschillen nog gro-ter. In de groep 55-64 jaar is het met 26,3% veel hoger dan het gemiddelde van 9,8% in die leef-tijdsgroep.    

Landelijk gezien was het percentage kinderen dat in **armoede** opgroeit onder Antilliaans-Nederlandse kinderen het hoogst van alle migrantengroepen. In Den Haag is het ook zorgwekkend, maar is de armoede onder Marokkaans-Nederlandse gezinnen met 53% nog hoger. Van de Antilli-aans-Nederlandse kinderen groeit 42% op in een minimahuishouden. Bij kinderen met een Neder-landse achtergrond is dat 9%.   
 
Opvallend qua *gezondheid* is een hoog percentage van de bewoners met een Antilliaanse achter-grond heeft last van overgewicht en het relatief vaak voorkomen van GGz problemen.   

Verder valt op dat er onder deze groep relatief veel **tienermoeders** zijn en **gezins- opvoedingsproblematiek* veel voorkomt. Het gebruik van **jeugdzorg** is enorm hoog, ook veel hoger dan bij andere migrantengroepen. Uit de literatuur blijkt dat er onder alle migrantengroepen, ook onder Antilli-aanse Nederlanders drempels worden ervaren om zelf naar de jeugdzorg te gaan. Des te opvallen-der is het hoge gebruik. Landelijk gezien is dat overigens vergelijkbaar. In de literatuur komt naar voren dat het gebruik hoog is, maar het vroegtijdig bereik en de aansluiting bij de behoefte van de gezinnen niet altijd optimaal is.    

De oververtegenwoordiging van Antilliaans-Nederlandse inwoners in de *criminaliteit* is hoog. Dit zien we niet alleen in de Haagse cijfers, maar ook in de landelijke cijfers. Van alle Antilliaanse-Nederlanders in Den Haag was 6,3% verdacht van criminaliteit, terwijl van alle inwoners uit Den Haag in totaal 2,2% verdacht werd van criminaliteit. Dit is vergelijkbaar met Nederland als geheel. Hier liggen deze percentages op 6,1% voor alle Antilliaanse-Nederlanders en op 1,7% voor alle in-woners met een Nederlandse achtergrond in totaal. Het valt op dat in Den Haag onder Antilliaans-Nederlandse verdachten relatief vaak oudere verdachten voorkomen (45-64 jaar). Bovendien zijn het relatief veel ?veelplegers? (22% is veelpleger t.o.v. 17% als gemiddelde) en weinig beginners (8% t.o.v. 40% als gemiddelde). Het type delict dat wordt gepleegd door inwoners met een Antilli-aanse achtergrond is met name vermogensdelicten.  In de **jeugdreclassering** is het percentage relatief hoog. Hoger dan andere groepen met een migratieachtergrond. In 2016 had 0,8% van alle jongeren in Den Haag een maatregel jeugdreclassering. Onder jongeren met een Antilliaanse ach-tergrond was dat 2,0%. Met een Marokkaanse achtergrond was het 1,8%. Ook in Amsterdam en Rotterdam hadden relatief veel jongeren met een Antilliaanse achtergrond die te maken met de Jeugdreclassering.    

Bovenstaande geeft aan dat een relatief groot deel van de inwoners met een Antilliaanse achter-grond in Den Haag kampt met problemen. Het verdient aanbeveling om samen met vertegen-woordigers van deze groep te zoeken naar gerichte oplossingen die goed aansluiten bij deze groep. Preventie lijkt vooral nodig op het gebied van armoedebestrijding, opvoedingsondersteuning, het voorkomen van uitval en een criminele loopbaan. 


