---
title: "Zorggebruik algemeen"
description: |
  Over het zorggebruik van Antillianen in Den Haag.
author:
  - name: Harrie Jonkman
    url: https://harriejonkman.nl/harriejonkman
date: 11-06-2018
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Zorggebruik algemeen {-} 

**Zorggebruik onder Haagse inwoners**   
Uit literatuur blijkt dat het aanbod en de werkwijze binnen de Nederlandse gezondheidszorg niet altijd goed aansluit op de behoeften van mensen met een migratieachtergrond. In Den Haag is daarom in 2016 een onderzoek uitgevoerd door het Verwey-Jonker Instituut naar het gebruik van verschillende vormen van zorg onder de Haagse inwoners [@Hamdi2017]. In het onderzoek, uitgevoerd door  Hamdi e.a. (2017), is een verschil zichtbaar tussen het gebruik van huisartsen- en ziekenhuiszorg enerzijds, en de thuiszorg, GGZ en ouderenzorg ander-zijds.   

**Oververtegenwoordiging**   
*Huisartsenzorg*	Van de Haagse inwoners met een Antilliaanse achtergrond heeft 83% in het afgelopen jaar de huisarts minimaal 1 keer bezocht. Hiermee zijn zij samen met inwoners met een Marokkaanse achtergrond de hoogste gebruikers van huisartsenzorg. Bij inwoners met een Turkse en Surinaamse achtergrond ligt dit op 80%. Bij inwoners met een Nederlandse achtergrond heeft 77% de huisarts minimaal 1 keer in het afgelopen jaar bezocht.     
*Ziekenhuiszorg*	Over het gebruik van ziekenhuiszorg zijn geen specifieke cijfers beschik-baar, maar ook hier is het beeld dat inwoners met een migratieachtergrond vaker contact hebben met het ziekenhuis.   

**Ondervertegenwoordiging**  
Van zowel *ouderenzorg, thuiszorg* als *GGZ* zijn ook geen specifieke cijfers beschikbaar, maar is het beeld dat Haagse inwoners met een migratieachtergrond deze vormen van zorg moeilijk weten te vinden.   

**Mogelijke verklaringen**   
Inwoners met een Antilliaanse achtergrond weten bij lichamelijke klachten de weg naar de zorg (huisarts of ziekenhuis) goed te vinden. Wanneer er echter sprake is van niet-lichamelijke klachten, maar meer van ondersteuning (zoals bij ouderenzorg of thuiszorg) of psychische klachten (GGZ) weten zij de weg naar hulp minder goed te vinden.   

Verklaringen die worden gegeven voor de ondervertegenwoordiging van Antilliaanse-Nederlanders in de ouderenzorg, thuiszorg en GGZ zijn: 
- schaamte/taboe (GGZ); 
- eerst een band willen opbouwen voordat ze het achterste van hun tong laten zien (GGZ); 
- gebrek aan kennis van het zorgsysteem, waardoor ze niet weten waar ze gebruik van kun-nen maken;
- taalbarriere, waardoor ze niet altijd weten waar ze gebruik van kunnen maken (Thuiszorg); 
- zorg wordt ook vaak binnen familie geregeld (Ouderenzorg).[@Hamdi2017].


