---
title: "Criminaliteit"
description: |
  Over criminaliteit van Antilliaanse jongeren in Den Haag.
author:
  - name: Harrie Jonkman
    url: https://harriejonkman.nl/harriejonkman
date: 11-06-2018
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Criminaliteit {-}

**Verdachten van een delict**    
De oververtegenwoordiging van Marokkaans-Nederlandse en Antilliaans-Nederlandse inwoners is hoog. Dit zien we niet alleen in de Haagse cijfers, maar ook in de landelijke cijfers. Van alle Antilli-aanse-Nederlanders in Den Haag is 6,3% verdacht (geweest) van criminaliteit, terwijl van alle inwo-ners uit Den Haag in totaal 2,2% verdacht is (geweest) van criminaliteit. In Rotterdam ligt dit percen-tage iets hoger: van alle Antilliaanse-Nederlanders is 7,3% verdacht (geweest), terwijl het in Am-sterdam weer iets lager ligt (4,1%). In Nederland als geheel liggen deze percentages op 6,1% voor alle Antilliaanse-Nederlanders en op 1,7% voor alle inwoners met een Nederlandse achtergrond in totaal.    

**Oudere verdachten**    
Tevens valt op dat in Den Haag onder Antilliaans-Nederlandse verdachten relatief vaak oudere ver-dachten voorkomen (45-64 jaar). Bovendien zijn het relatief veel veelplegers (22% is veelpleger t.o.v. 17% als gemiddelde) en weinig beginners (8% t.o.v. 40% als gemiddelde). Het type delict dat wordt gepleegd door inwoners met een Antilliaanse achtergrond is met name vermogensdelicten.

**Oververtegenwoordiging**
Verdachten van een delict hebben vaker dan op grond van hun aandeel in de bevolking verwacht mag worden, een niet-westerse achtergrond. Van alle verdachten in Nederland is 3,7% van Antilli-aanse afkomst, terwijl hun aandeel in de Nederlandse bevolking slechts 0,9% bedraagt.


**Mogelijke verklaringen**
Trees Pels beschrijft in ?Het kennisfundament t.b.v. de aanpak van criminele Marokkaanse jonge-ren? uitgebreid specifieke risicofactoren bij Antilliaanse jongeren, waardoor zij vaker in de criminali-teit voorkomen dan andere groepen [@Pels2008]. Pels behandelt de risicofactoren op vier niveaus: de jongere zelf, het gezin, de peergroup en de omgeving.
 
Op het niveau van de jongere wordt de beperkte Nederlandse taal, gebrekkig sociaal net-werk, gebrek aan sociale binding met de Nederlandse samenleving (gerelateerd aan migratiege-schiedenis), geen conventionele normen en waarden (uitstralen van materi?le rijkdom), weinig onder de indruk van Nederlandse straffen en kwetsbaarder door wensstatus te tonen, maar een lage sociale status en negatieve bejegening door de samenleving genoemd.

Op gezinsniveau wordt genoemd: de relatief veel eenoudergezinnen en tienermoeder-schap, sekse-specifieke opvoeding, opvoedingsonzekerheid, haperende interactie met de jeugd-zorg en een pedagogisch eenzijdige benadering (autoritair, eenzijdig met accent op sturing, weinig persoonlijke aandacht, eenrichtingsverkeer in communicatie). Daarnaast geldt ook voor het ge-zinsniveau de beperkingen in de Nederlandse taalvaardigheid en het sociale netwerk en het ont-breken van conventionele normen en waarden (het uitstralen van materiele rijkdom).

Op het niveau van de peergroup komen de volgende risicofactoren naar voren: de grote in-vloed van de peergroup (onderlinge afhankelijkheid, groepsdruk, collectieve behoeftebevredi-ging), het weinig contact met andere etnische jongeren, de groepsdynamiek en de straatcultuur (geen conventionele normen en waarden, maar waardering en status door delinquent gedrag).

Ten slotte wordt op het niveau van de omgeving de ambivalente relatie met Nederland, risicos van het leven in concentratiewijken, de zwakke pedagogische infrastructuur, een beperkt ondersteunend netwerk, gebrek aan interculturele competenties bij instituties en de onvoldoende mogelijkheden en methodieken van instituties om deze gezinnen goed te bereiken en helpen, genoemd. 


