---
title: "Gezondheid"
description: |
  Over de gezondheid van Antillianen in Den Haag.
author:
  - name: Harrie Jonkman
    url: https://harriejonkman.nl/harriejonkman
date: 11-06-2018
output:
  radix::radix_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Gezondheid {-}

**Gezondheid Haagse inwoners**   
Uit de Haagse Integratiemonitor [@DeGruijter2014] blijkt dat er verschil is in de mate van gezondheid tussen inwoners met een migratieachtergrond en inwoners zonder een migratie-achtergrond. Inwoners met een migratieachtergrond hebben meer dan gemiddeld matig of ernstig overgewicht en lopen meer dan gemiddeld kans op het ontwikkelen van een angststoornis of een depressie. Daarnaast ervaren zij hun gezondheid minder dan gemiddeld als goed of uitstekend.     

**Antilliaans-Nederlandse inwoners**    
Ruim driekwart van de inwoners met een Antilliaanse achtergrond hebben matig of ernstig over-gewicht. Dit is het hoogste percentage van alle inwoners in Den Haag. Ruim een vijfde (22,8%) heeft ook kans op een angststoornis en depressie. Alleen inwoners met een Turkse achtergrond hebben een hoger percentage (25,6%).
Ten slotte scoren inwoners met een Antilliaanse achtergrond ten opzichte van alle inwoners met een migratieachtergrond, gemiddeld op de vraag of ze hun gezondheid als goed/uitstekend erva-ren (65,8% antwoordt met ja).


**Mogelijke verklaringen**   
Als verklaring van de hogere percentages overgewicht bij Antilliaanse-Nederlanders wordt aange-geven dat dit samenhangt met bepaalde ongezonde voedingsgewoonten en het feit dat ze minder bewegen [@VanWijk2010].

*Voedingsgewoonten*   
Uit onderzoek van Vermeeren komt naar voren dat op de Caraiben nauwelijks dierlijke melkproducten worden gegeten (ook vanwege een lactose-intolerantie), en dat er in plaats van dierlijke melkproducten meer kokosmelk wordt gebruikt [@Vermeeren2007]. Daarnaast zijn ze afhankelijk van wat er qua eten verbouwd kan worden (vanwege het droge klimaat) en zijn ze voor veel groente- en fruitsoorten afhankelijk van import waardoor deze niet veel gegeten worden. Wel wordt er veel graan en ma?s verbouwd. Deze producten zijn echter zelden volkoren en worden vaak verwerkt tot pap en pasteitjes, die vettig zijn. Daar staat tegenover dat er wel veel vis in plaats van vlees gege-ten.  Echter, de bereiding van eten gebeurt ook vaak met kokosolie, in plaats van margarine of olijfolie, wat vetter is. 

*Bewegen*   
Uit eerder onderzoek blijkt dat 37% van de vrouwen met een Antilliaanse achtergrond sporten, tegenover 56% van de vrouwen met een Nederlandse achtergrond (Breedveld & Thiessen-Raaphorst, 2006). Dit kan volgens Breedveld & Thiessen-Raaphorst (2006) verklaard worden door-dat er op de Antillen in mindere mate sprake is van een sportcultuur. Andere belemmerende facto-ren voor deelname aan sportverenigingen blijken van financi?le, culturele en sociale aard, waaron-der abonnementskosten en discriminatie [@Vermeeren2007].  

*Angst en depressie*
De verhoogde kans op angst en depressie onder niet alleen Antilliaanse-Nederlanders maar onder vrijwel alle inwoners met een niet-westerse achtergrond hangt samen met hun positie in de maat-schappij. Zo geven Selten et al. aan in hun studie naar de behandeling van stemmingsstoornissen onder migranten aan dat met name de stressvolle positie van niet-westerse migranten in de Nederlandse samenleving negatieve consequenties heeft op hun mentale gezondheid[@Selten2012]. 



